# Generated by Django 3.2.7 on 2021-10-13 15:03

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_listing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=64)),
                ('listing_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='auctions.listing')),
                ('watchlist_user', models.ForeignKey(default=auctions.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
