# Generated by Django 3.2.7 on 2021-10-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211014_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='user_watchlist',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listings',
            new_name='watchlist_items',
        ),
    ]
