# Generated by Django 3.2.7 on 2021-10-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211015_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='top_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auctions.bid'),
        ),
    ]
