# Generated by Django 3.2.7 on 2021-10-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_top_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='top_bid',
            new_name='bids',
        ),
    ]
