# Generated by Django 3.2.7 on 2021-10-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_top_bid_listing_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
    ]
