# Generated by Django 3.2.7 on 2021-12-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='user',
        ),
    ]
