# Generated by Django 3.2.9 on 2021-12-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211208_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='category', to='auctions.Category'),
        ),
    ]
